### ISSUE TITLE
row update 在更新數值的時候會把 "0052" 和 "52" 判斷為一樣因此沒辦法正常更新

### ISSUE THREAD

**Issue by chuhw** [pixnet/pixframework#62]
看起來是 pixframework 下的 Row.php

![image](https://user-images.githubusercontent.com/672371/123499889-730d5e00-d66c-11eb-88fd-aae549c48c3e.png)

這邊的判斷應該是要 !== 而不是 !=
是吧 XD

**Comment by ronnywang** [comment]
這個修改有點怕會造成舊有的程式邏輯變更而出錯

我比較建議的作法是，增加檢查如果
Pix_Setting::set('Table:RowUpdateIdentity', true);
就會採用 === 的強比對，預設還是照舊 == 的弱比對

**Comment by chuhw** [comment]
不過這應該是 bug 要 patch 吧🤣
看原本 pixnet 的影響如果太大的話要不要額外 fix
但 open source 的是不是應該以正規處理為主啊

我這邊是自己先 patch 了

**Comment by jnlin** [comment]
@chuhw PR welcome~~

**Comment by arrack** [comment]
已修正，感謝回報
https://github.com/pixnet/pixframework/commit/0c393579d84640fb9d7304f2da4cb5a3a337d052

**Comment by chuhw** [comment]
thanks all
